backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/img"
public_folder: "/assets/img"

collections:
- label: "Pages"
  name: "pages"
  files:
  - label: "Im Brückle"
    name: "homepage"
    file: "src/pages/index.md"
    fields:
    - {label: "Content", name: "content", widget: "markdown" }
  - label: "Hoflädle"
    name: "hofladle"
    file: "src/pages/hofladle.md"
    fields:
    - {label: "Content", name: "content", widget: "markdown" }
  - label: "Brennerei"
    name: "brennerei"
    file: "src/pages/brennerei.md"
    fields:
    - {label: "Content", name: "content", widget: "markdown" }
  - label: "Weinlaube"
    name: "weinlaube"
    file: "src/pages/weinlaube.md"
    fields:
    - {label: "Content", name: "content", widget: "markdown" }
  - label: "Kontakt"
    name: "kontakt"
    file: "src/pages/kontakt.md"
    fields:
    - {label: "Content", name: "content", widget: "markdown" }

